name: 6k2-services

services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file: 
      - .env
      - /data/secrets/common/auth/auth_token.env
    environment:
      TIMEWEBCLOUD_AUTH_TOKEN_FILE: /run/secrets/timeweb_auth_token
    volumes:
      - certificates:/usr/local/share/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik:ro
    secrets:
      - timeweb_auth_token
    labels:
      traefik.enable: 'true'
      
      traefik.http.routers.traefik-static.priority: 100
      traefik.http.routers.traefik-static.service: api@internal
      traefik.http.routers.traefik-static.rule: >
        Host(`traefik.6k2.ru`) && (
        PathPrefix(`/static/`) ||
        PathRegexp(`/manifest\.json$`) || 
        PathRegexp(`/favicon\.(ico|png|svg)$`) )

      traefik.http.routers.traefik.priority: 1
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: ip-whitelist@file, auth@file
      traefik.http.routers.traefik.rule: >
        Host(`traefik.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 128mb


  authelia:
    container_name: authelia
    image: authelia/authelia:4
    restart: unless-stopped
    user: 1000:1000
    env_file: .env
    environment:
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/db_password_authelia
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/lldap_password_authelia
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/smtp_password_authelia
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_secret
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /run/secrets/redis_password
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_reset_password_secret
    volumes:
      - ./authelia:/config:ro
    secrets:
      - db_password_authelia
      - redis_password
      - lldap_password_authelia
      - smtp_password_authelia
      - authelia_storage_encryption_key
      - authelia_session_secret
      - authelia_reset_password_secret
    expose: [ 9091 ]    # Web front-end and ForwardAuth endpoint
    labels:
      traefik.enable: 'true'
      traefik.http.routers.authelia.rule: >
        Host(`authelia.6k2.ru`) ||
        Host(`xn--c1akhkc.xn--62-2lc.xn--p1ai`) ||
        Host(`xn--c1akhkc.xn--b1ayja.xn--p1ai`)
    depends_on:
      - postgres
      - redis
      - lldap
    deploy:
      resources:
        limits:
          memory: 128mb


  authentik:
    container_name: authentik
    image: ghcr.io/goauthentik/server:2026.2
    restart: unless-stopped
    command: server
    env_file: 
      - .env
      - authentik/.env
    environment:
      AUTHENTIK_LOG_LEVEL: ${LOG_LEVEL:-warning}
    volumes:
      - authentik_data:/data
    secrets:
      - db_password_authentik
      - authentik_session_secret
      - authentik_admin_password
    expose: [ 9000 ]    # Web front-end and ForwardAuth endpoint
    labels:
      traefik.enable: 'true'
      traefik.http.routers.authentik.rule: >
        Host(`authentik.6k2.ru`) ||
        Host(`auth.6k2.ru`)
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 2gb


  authentik-worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2026.2
    restart: unless-stopped
    command: worker
    env_file: 
      - .env
      - authentik/.env
    environment:
      AUTHENTIK_LOG_LEVEL: ${LOG_LEVEL:-warning}
    volumes:
      - authentik_data:/data
    secrets:
      - db_password_authentik
      - authentik_session_secret
      - authentik_admin_password
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 2gb


  dex:
    container_name: dex
    image: dexidp/dex:v2.45.1
    restart: unless-stopped
    env_file: .env
    environment:
      DEX_LOG_LEVEL: ${LOG_LEVEL:-warn}
    volumes:
      - ./dex:/etc/dex:ro
    secrets:
      - oauth_yandex_client_secret
    expose: [ 5556 ]    # OpenID Connect service endpoint
    labels:
      traefik.enable: 'true'

      # Publicly allow redirects to /auth for OIDC authentication flow
      traefik.http.routers.dex-auth.priority: 100
      traefik.http.routers.dex-auth.rule: >
        Host(`dex.6k2.ru`) && ( Path(`/auth`) || PathPrefix(`/auth/`) )

      # Everything else should only be accessed from within Authentik
      traefik.http.routers.dex.priority: 1
      traefik.http.routers.dex.middlewares: ip-whitelist@file
      traefik.http.routers.dex.rule: >
        Host(`dex.6k2.ru`)

    deploy:
      resources:
        limits:
          memory: 128mb


  lldap:
    container_name: lldap
    image: lldap/lldap:stable-alpine-rootless
    restart: unless-stopped
    env_file:
      - .env
      - /data/secrets/postgres/auth/lldap_url.env
    environment:
      RUST_LOG: warn
      LLDAP_KEY_SEED_FILE: /run/secrets/lldap_key_seed
      LLDAP_JWT_SECRET_FILE: /run/secrets/lldap_jwt_secret
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/lldap_password_admin
      LLDAP_LDAP_BASE_DN: dc=6k2,dc=ru
    volumes:
      - ./lldap:/data:ro
    secrets:
      - lldap_key_seed
      - lldap_jwt_secret
      - lldap_password_admin
    expose: [ 17170 ]    # Web front-end 
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lldap.middlewares: ip-whitelist@file
      traefik.http.routers.lldap.rule: >
        Host(`users.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 128mb


  postgres:
    container_name: postgres
    image: postgres:18-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres_database:/var/lib/postgresql
    secrets:
      - db_password_postgres
      - db_password_authelia
      - db_password_authentik
      - db_password_lldap
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    deploy:
      resources:
        limits:
          memory: 512mb


  redis:
    container_name: redis
    image: bitnami/redis
    restart: unless-stopped
    env_file: .env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    volumes:
      - ./redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
      - redis_data:/bitnami/redis/data
    secrets:
      - redis_password
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli --no-auth-warning -a "$$(cat $$REDIS_PASSWORD_FILE)" ping | grep PONG
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 1s
    deploy:
      resources:
        limits:
          memory: 512mb


  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower
    restart: unless-stopped
    env_file: .env
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_LOG_LEVEL: ${LOG_LEVEL:-warn}
    volumes:
      - /root/.docker/config.json:/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 128mb


  glances:
    container_name: glances
    image: nicolargo/glances:latest
    restart: unless-stopped
    env_file: .env
    environment:
      GLANCES_OPT: -w
    pid: host
    volumes:
      - /:/rootfs:ro
      - postgres_database:/postgres_database:ro
      - redis_data:/redis_data:ro
      - authentik_data:/authentik_data:ro
      - utility-bills_data:/utility-bills_data:ro
      - ./glances:/etc/glances:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    expose: [ 61208 ]    # Web front-end 
    labels:
      traefik.enable: 'true'
      traefik.http.routers.glances.middlewares: auth@file
      traefik.http.routers.glances.rule: >
        Host(`glances.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 256mb


  static:
    container_name: static
    image: nginx:1.29-alpine-slim
    restart: unless-stopped
    volumes:
      - ./static/web:/web:ro
      - ./static/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.static.rule: >
        Host(`static.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 128mb


  oss-2021:
    container_name: oss-2021
    image: moujikov/6k2_oss-2021
    restart: unless-stopped
    env_file: .env
    secrets:
      - auth_token
    labels:
      traefik.enable: 'true'

      # Private area requires authentication
      traefik.http.routers.oss-2021-private.priority: 100
      traefik.http.routers.oss-2021-private.middlewares: auth@file
      traefik.http.routers.oss-2021-private.rule: >
        Host(`2021.oss.6k2.ru`) && ( Path(`/-`) || PathPrefix(`/-/`) )

      # Public results don't require authentication
      traefik.http.routers.oss-2021.priority: 1
      traefik.http.routers.oss-2021.rule: >
        Host(`2021.oss.6k2.ru`) || 
        Host(`2021.xn--n1aga.xn--62-2lc.xn--p1ai`) ||
        Host(`2021.xn--b1ayja.xn--p1ai`)
    deploy:
      resources:
        limits:
          memory: 128mb


  oss-2023:
    container_name: oss-2023
    image: moujikov/6k2_oss-2023
    restart: unless-stopped
    env_file: .env
    secrets:
      - auth_token
    labels:
      traefik.enable: 'true'

      # Private area requires authentication
      traefik.http.routers.oss-2023-private.priority: 100
      traefik.http.routers.oss-2023-private.middlewares: auth@file
      traefik.http.routers.oss-2023-private.rule: >
        ( Host(`oss.6k2.ru`) || Host(`2023.oss.6k2.ru`) ) && ( Path(`/-`) || PathPrefix(`/-/`) )

      # Public results don't require authentication
      traefik.http.routers.oss-2023.priority: 1
      traefik.http.routers.oss-2023.rule: >
        Host(`oss.6k2.ru`) || 
        Host(`2023.oss.6k2.ru`) || 
        Host(`xn--n1aga.xn--62-2lc.xn--p1ai`) ||
        Host(`2023.xn--n1aga.xn--62-2lc.xn--p1ai`) || 
        Host(`xn--b1ayja.xn--p1ai`) || 
        Host(`2023.xn--b1ayja.xn--p1ai`)
    deploy:
      resources:
        limits:
          memory: 128mb


  osch-2024:
    container_name: osch-2024
    image: moujikov/6k2_osch-2024
    restart: unless-stopped
    env_file: .env
    secrets:
      - auth_token
    labels:
      traefik.enable: 'true'

      # Private area requires authentication
      traefik.http.routers.osch-2024-private.priority: 100
      traefik.http.routers.osch-2024-private.middlewares: auth@file
      traefik.http.routers.osch-2024-private.rule: >
        Host(`2024.os4.6k2.ru`) && ( Path(`/-`) || PathPrefix(`/-/`) )

      # Public results don't require authentication
      traefik.http.routers.osch-2024.priority: 1
      traefik.http.routers.osch-2024.rule: >
        Host(`2024.os4.6k2.ru`) || 
        Host(`2024.xn--n1ags.xn--62-2lc.xn--p1ai`)
    deploy:
      resources:
        limits:
          memory: 128mb


  osch-2025:
    container_name: osch-2025
    image: moujikov/6k2_osch-2025
    restart: unless-stopped
    env_file: .env
    secrets:
      - auth_token
    labels:
      traefik.enable: 'true'

      # Private area requires authentication
      traefik.http.routers.osch-2025-private.priority: 100
      traefik.http.routers.osch-2025-private.middlewares: auth@file
      traefik.http.routers.osch-2025-private.rule: >
        ( Host(`os4.6k2.ru`) || Host(`2025.os4.6k2.ru`) ) && ( Path(`/-`) || PathPrefix(`/-/`) )

      # Public results don't require authentication
      traefik.http.routers.osch-2025.priority: 1
      traefik.http.routers.osch-2025.rule: >
        Host(`os4.6k2.ru`) || 
        Host(`2025.os4.6k2.ru`) || 
        Host(`xn--n1ags.xn--62-2lc.xn--p1ai`) ||
        Host(`2025.xn--n1ags.xn--62-2lc.xn--p1ai`)
    deploy:
      resources:
        limits:
          memory: 128mb


  utility-bills:
    container_name: utility-bills
    image: moujikov/6k2_utility-bills
    restart: unless-stopped
    env_file: .env
    secrets:
      - auth_token.nginx.conf
    volumes:
      - utility-bills_data:/var/app-data
    labels:
      traefik.enable: 'true'
      traefik.http.routers.utility-bills.middlewares: auth@file
      traefik.http.routers.utility-bills.rule: >
        Host(`bills.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 256mb


  alt-chat:
    container_name: alt-chat
    image: moujikov/6k2_alt-chat
    restart: unless-stopped
    env_file: .env
    secrets:
      - auth_token.nginx.conf
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
      traefik.enable: 'true'
      traefik.http.routers.alt-chat.middlewares: auth@file
      traefik.http.routers.alt-chat.rule: >
        Host(`a4.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 128mb

  mailer:
    container_name: mailer
    image: mwader/postfix-relay:1.2
    restart: unless-stopped
    env_file: .env
    environment:
      SASL_Passwds: /etc/postfix/sasl/sasl_passwds
      POSTFIX_smtpd_sasl_auth_enable: yes
      POSTFIX_smtpd_sasl_security_options: noanonymous
      POSTFIX_smtpd_relay_restrictions: permit_sasl_authenticated,reject
      OPENDKIM_DOMAINS: 6k2.ru=mailing-list
    volumes:
      - /data/secrets/smtp/dkim:/etc/opendkim/keys/6k2.ru:ro
      - /data/secrets/smtp/auth/passwords.hashed:/etc/postfix/sasl/sasl_passwds:ro
    expose: [ 25 ]    # SMTP endpoint
    labels:
      traefik.enable: 'true'
      traefik.http.routers.mailer.entrypoints: smtps
      traefik.http.routers.mailer.rule: >
        Host(`smtp.6k2.ru`)
    deploy:
      resources:
        limits:
          memory: 256mb


volumes:
  certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/volumes/certificates
  postgres_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/volumes/postgres_database
  authentik_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/volumes/authentik_data
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/volumes/redis_data
  utility-bills_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/volumes/utility-bills_data


secrets:
  auth_token:
    file: /data/secrets/common/auth/auth_token
  auth_token.nginx.conf:
    file: /data/secrets/common/auth/auth_token.nginx.conf
  timeweb_auth_token:
    file: /data/secrets/oauth/tokens/timeweb
  oauth_yandex_client_secret:
    file: /data/secrets/oauth/secrets/yandex
  db_password_postgres:
    file: /data/secrets/postgres/auth/postgres_password
  db_password_authelia:
    file: /data/secrets/postgres/auth/authelia_password
  db_password_authentik:
    file: /data/secrets/postgres/auth/authentik_password
  db_password_lldap:
    file: /data/secrets/postgres/auth/lldap_password
  redis_password:
    file: /data/secrets/redis/auth/redis_password
  smtp_password_authelia:
    file: /data/secrets/smtp/auth/authelia_password
  authelia_storage_encryption_key:
    file: /data/secrets/authelia/keys/storage_encryption_key
  authelia_session_secret:
    file: /data/secrets/authelia/keys/session_secret
  authelia_reset_password_secret:
    file: /data/secrets/authelia/keys/reset_password_secret
  authentik_session_secret:
    file: /data/secrets/authentik/keys/session_secret
  authentik_admin_password:
    file: /data/secrets/authentik/auth/admin_password
  lldap_key_seed:
    file: /data/secrets/lldap/keys/key_seed
  lldap_jwt_secret:
    file: /data/secrets/lldap/keys/jwt_secret
  lldap_password_admin:
    file: /data/secrets/lldap/auth/admin_password
  lldap_password_authelia:
    file: /data/secrets/lldap/auth/authelia_password
