api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@6k2.ru
      storage: /usr/local/share/traefik/certs/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG

providers:
  docker: {}
