server:
  address: tcp://:80/
  asset_path: /config/assets

authentication_backend:
  file:
    path: /auth/users.yml
    watch: true
    search:
      email: true

storage:
  postgres:
    address: tcp://database:5432
    database: authelia
    username: authelia

access_control:
  rules:
    - domain:
      - 'oss.6k2.ru'
      - '*.oss.6k2.ru'
      - 'xn--b1ayja.xn--p1ai'           # восс.рф
      - '*.xn--b1ayja.xn--p1ai'         # *.восс.рф
      resources:
        - '^/-$'
        - '^/-/'
      policy: one_factor
    - domain:
      - 'oss.6k2.ru'
      - '*.oss.6k2.ru'
      - 'xn--b1ayja.xn--p1ai'           # восс.рф
      - '*.xn--b1ayja.xn--p1ai'         # *.восс.рф
      policy: bypass
    - domain: '*.6k2.ru'
      policy: one_factor
    - domain: '*.xn--b1ayja.xn--p1ai'   # *.восс.рф
      policy: one_factor
  default_policy: deny

session:
  inactivity: 1y
  expiration: 1y
  remember_me: -1
  name: auth_session
  cookies:
    - domain: 6k2.ru
      authelia_url: https://auth.6k2.ru
      default_redirection_url: https://6k2.ru
    - domain: xn--b1ayja.xn--p1ai                             # восс.рф
      authelia_url: https://xn--c1akhkc.xn--b1ayja.xn--p1ai   # логин.восс.рф
      default_redirection_url: https://xn--b1ayja.xn--p1ai    # восс.рф

notifier:
  smtp:
    startup_check_address: test@6k2.ru
    address: submissions://smtp.yandex.ru:465
    username: andrey.muzhikov@6k2.ru
    sender: ТСЖ «Варшавская 6-2» <no-reply@6k2.ru>
    identifier: 6k2.ru
    subject: '[Authelia] {title}'

log:
  level: info
