http:

  middlewares:
    admin_auth:
      basicAuth:
        removeheader: true
        usersFile: /run/secrets/admins
    user_auth:
      basicAuth:
        removeheader: true
        usersFile: /run/secrets/users
