http:

  middlewares:
    auth:
      chain:
        middlewares:
          - authentik
          - auth-headers

    authelia:
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth
        maxResponseBodySize: 4096
        authResponseHeaders: 
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

    authentik:
      forwardAuth:
        address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
        maxResponseBodySize: 16384
        authResponseHeaders:
          - X-Authentik-Username
          - X-Authentik-Groups
          - X-Authentik-Email
          - X-Authentik-Name

    auth-headers:
      plugin:
        htransformation:
          Rules:
            - Type: Set
              Header: Authorization
              Value: Bearer {{ env "SERVICES_AUTH_TOKEN" }}
            - Type: Set
              Header: X-Auth-Token
              Value: {{ env "SERVICES_AUTH_TOKEN" }}
            - Type: Rename
              Header: X-Authentik-Username
              Value: X-Auth-User
            - Type: Rename
              Header: X-Authentik-Groups
              Value: X-Auth-Groups
            - Type: Rename
              Header: X-Authentik-Email
              Value: X-Auth-User-Email
            - Type: Rename
              Header: X-Authentik-Name
              Value: X-Auth-User-Name

    ip-whitelist:
      ipAllowList:
        sourceRange:
          - 172.18.0.1          # Requests from within Docker network (SRC-NATed by Docker)
          - 93.191.63.222       # Andrey's home
          - 195.208.188.0/24    # Andrey's home

    redirect-var62:
      redirectRegex:
        regex: ^https://(.*\.)?var62\.ru(/?.*)$
        replacement: https://${1}6k2.ru${2}

  routers:
    redirect-var62:
      rule: >
        Host(`var62.ru`) ||
        HostRegexp(`^.*\.var62\.ru$`)
      middlewares: redirect-var62
      service: noop@internal
