http:

  middlewares:
    admin-auth:
      digestAuth:
        removeHeader: true
        usersFile: /run/secrets/admins
    user-auth:
      digestAuth:
        removeHeader: true
        usersFile: /run/secrets/users
    ip-whitelist:
      ipAllowList:
        sourceRange:
          - "93.191.63.222/32"
