api:
  dashboard: true
  disableDashboardAd: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    observability:
      accessLogs: false
      metrics: false
      tracing: false
  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@6k2.ru
      storage: /usr/local/share/traefik/certs/acme.json
      dnsChallenge:
        provider: timewebcloud

      # httpChallenge:
      #   entryPoint: web

log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
