api:
  dashboard: true
  disableDashboardAd: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    observability:
      accessLogs: false
      metrics: false
      tracing: false
  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "6k2.ru"
            sans:
              - "*.6k2.ru"
              - "*.oss.6k2.ru"
              - "*.osch.6k2.ru"
              - "*.os4.6k2.ru"
          - main: "var62.ru"
            sans:
              - "*.var62.ru"
              - "*.oss.var62.ru"
              - "*.osch.var62.ru"
              - "*.os4.var62.ru"
          - main: "xn--62-2lc.xn--p1ai"             # 6к2.рф
            sans:
              - "*.xn--62-2lc.xn--p1ai"             # *.6к2.рф
              - "*.xn--n1aga.xn--62-2lc.xn--p1ai"   # *.осс.6к2.рф
              - "*.xn--n1ags.xn--62-2lc.xn--p1ai"   # *.осч.6к2.рф
          - main: "xn--b1ayja.xn--p1ai"             # восс.рф
            sans:
              - "*.xn--b1ayja.xn--p1ai"             # *.восс.рф

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@6k2.ru
      storage: /usr/local/share/traefik/certs/acme.json
      dnsChallenge:
        provider: timewebcloud
      httpChallenge:
        entryPoint: web

log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
