api:
  dashboard: true
  disableDashboardAd: true

log:
  level: WARN

# accessLog:
#   format: json
#   fields:
#     defaultMode: keep
#     headers:
#       defaultMode: keep
#       names:
#         X-Auth-Token: drop
#         Authorization: drop

experimental:
  plugins:
    htransformation:
      moduleName: github.com/tomMoulard/htransformation
      version: v0.3.3

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    observability:
      accessLogs: false
      metrics: false
      tracing: false

  websecure:
    address: ':443'
    asDefault: true
    forwardedHeaders:
      trustedIPs:
        - 172.18.0.1        # Requests from within Docker network (SRC-NATed by Docker)
    http:
      tls:
        certResolver: letsencrypt
        domains:

          - main: 6k2.ru                            # Domain: 6k2.ru
            sans:                                   # Subdomains:
              - '*.6k2.ru'                          #   *.6k2.ru
              - '*.oss.6k2.ru'                      #   *.oss.6k2.ru
              - '*.osch.6k2.ru'                     #   *.osch.6k2.ru
              - '*.os4.6k2.ru'                      #   *.os4.6k2.ru

          - main: var62.ru                          # Domain: var62.ru
            sans:                                   # Subdomains:
              - '*.var62.ru'                        #   *.var62.ru
              - '*.oss.var62.ru'                    #   *.oss.var62.ru
              - '*.osch.var62.ru'                   #   *.osch.var62.ru
              - '*.os4.var62.ru'                    #   *.os4.var62.ru

          - main: xn--62-2lc.xn--p1ai               # Domain: 6к2.рф
            sans:                                   # Subdomains:
              - '*.xn--62-2lc.xn--p1ai'             #   *.6к2.рф
              - '*.xn--n1aga.xn--62-2lc.xn--p1ai'   #   *.осс.6к2.рф
              - '*.xn--n1ags.xn--62-2lc.xn--p1ai'   #   *.осч.6к2.рф

          - main: xn--b1ayja.xn--p1ai               # Domain: восс.рф
            sans:                                   # Subdomains:
              - '*.xn--b1ayja.xn--p1ai'             #   *.восс.рф

  smtps:
    address: ':465'


certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@6k2.ru
      storage: /usr/local/share/traefik/certs/acme.json
      dnsChallenge:
        provider: timewebcloud
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
