worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;

  server {
    listen 80;
    root /web;

    location / {
      if ($request_method = 'GET') {
        add_header Access-Control-Allow-Origin *.6k2.ru;
        add_header Access-Control-Allow-Origin *.var62.ru;
        add_header Access-Control-Allow-Origin *.xn--62-2lc.xn--p1ai;   # *.6к2.рф
        add_header Access-Control-Allow-Origin *.xn--b1ayja.xn--p1ai;   # *.восс.рф
      }
    }
  }
}
